import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Hero from '@/components/Hero';
import { Parallax } from 'react-parallax';



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Parallax bgImage={"img.jpg"} bgImageAlt="background image" strength={200} >
        <div className="content h-screen">
          <div className="text-content absolute top-1/2 left-1/2 py-1 px-4 -translate-x-1/2 -translate-y-1/2 bg-gray-600 text-white rounded-full text-xl">
          My Parallax - 0
          </div>
        </div>
      </Parallax>
      <Parallax bgImage={"img2.jpg"} bgImageAlt="background image" strength={200} >
        <div className="content h-screen">
          <div className="text-content absolute top-1/2 left-1/2 py-1 px-4 -translate-x-1/2 -translate-y-1/2 bg-gray-600 text-white rounded-full text-xl">
            My Parallax - 1
          </div>
        </div>
      </Parallax>
      <Parallax bgImage={"img3.jpg"} bgImageAlt="background image" strength={200} >
        <div className="content h-screen">
          <div className="text-content absolute top-1/2 left-1/2 py-1 px-4 -translate-x-1/2 -translate-y-1/2 bg-gray-600 text-white rounded-full text-xl">
          My Parallax - 2
          </div>
        </div>
      </Parallax>
      <Parallax bgImage={"img4.jpg"} bgImageAlt="background image" strength={200} >
        <div className="content h-screen">
          <div className="text-content absolute top-1/2 left-1/2 py-1 px-4 -translate-x-1/2 -translate-y-1/2 bg-gray-600 text-white rounded-full text-xl">
          My Parallax - 3
          </div>
        </div>
      </Parallax>
      <div className='h-screen'></div>
    </>
  )
}
